dist: trusty
sudo: false
language: java

env:
  global:
    - secure: aIw0AaE9hTmmS3Gfpd2/jQmPbwkiUTJKmpFLh2xZOKmCi4tZNXg/+Nw57jGnXn3Vn0RR5JScThjN4uZFLj3MkMECbKH4l3APD4AWm41E2bpZz7DtPo0ppQwGtAYBLwr/cYQvMTSa7WsoP8YYrwyjN50yJSVSO08uWFdNUKwttqk=
    - secure: RZfD/0Ksr8JYLVxXjkTY2Br5zeX//vQZ+EuvK8jnajoG7Cl468n3o6BtvELt9B7/aAFPO6HFPzqWNjQWFIZ3ts3s51vjwnaW6zszF6apVyQlnqG6mqdJtokezoNXJGpz4AD/+mrskN71HRMVVwSI+xrLInpufUjgw7t27Azczw8=

matrix:
  fast_finish: true
  allow_failures:
    - name: Apache JMeter master and Oracle JDK 8
    - name: Test with OpenJDK 16
    - name: Test with OpenJDK 17
  include:
    - name: Test with OpenJDK 11
      jdk: openjdk11
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Test with Oracle JDK 11
      jdk: oraclejdk11
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Test with Oracle JDK 8
      jdk: oraclejdk8
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Test with OpenJDK 13
      jdk: openjdk13
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Test with OpenJDK 16
      jdk: openjdk16
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Test with OpenJDK 17
      jdk: openjdk17
      script: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify
    - name: Apache JMeter master and Oracle JDK 8
      jdk: oraclejdk8
      script:
        - cd ..
        - git clone --depth 50 https://github.com/apache/jmeter.git
        - cd jmeter
        # TODO: remove --console=plain when upgrading dist from trusty
        - ./gradlew -PskipJavadoc publishToMavenLocal -Pjmeter.version=42.0 -PchecksumIgnore --console=plain
        - cd ../jmeter-maven-plugin
        - mvn -Djmeter.version=42.0-SNAPSHOT -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify

after_success:
  - ./deploy_to_sonatype.sh
  - bash <(curl -s https://codecov.io/bash) -v

cache:
  directories:
    - $HOME/.m2
